export const settingLocalization = {
  sign_up: {
    email_label: "メールアドレス",
    password_label: "パスワードを作成する",
    email_input_placeholder: "",
    password_input_placeholder: "",
    button_label: "新規登録",
    loading_button_label: "新規登録中 ... ",
    social_provider_text: " {{provider}} でサインイン",
    link_text: "新規登録する",
    confirmation_text: "メールで確認リンクを確認してください",
  },
  sign_in: {
    email_label: "メールアドレス",
    password_label: "あなたのパスワード",
    email_input_placeholder: "",
    password_input_placeholder: "",
    button_label: "サインイン",
    loading_button_label: "サインイン中 ... ",
    social_provider_text: " {{provider}} でサインイン",
    link_text: "すでにアカウントをお持ちですか? サインイン",
  },
  magic_link: {
    email_input_label: "メールアドレス",
    email_input_placeholder: "",
    button_label: "マジックリンクを送信する",
    loading_button_label: "マジックリンクを送信しています... ",
    link_text: "マジック リンク メールを送信する",
    confirmation_text: "メールでマジックリンクを確認してください",
  },
  forgotten_password: {
    email_label: "メールアドレス",
    password_label: "あなたのパスワード",
    email_input_placeholder: "あなたのメールアドレス",
    button_label: "パスワードのリセット手順を送信する",
    loading_button_label: "送信しています... ",
    link_text: "パスワードをお忘れですか? ",
    confirmation_text: "メールでパスワードリセッ リンクを確認してください",
  },
  update_password: {
    password_label: "新しいパスワード",
    password_input_placeholder: "新しいパスワード",
    button_label: "パスワードの更新",
    loading_button_label: "パスワードを更新しています... ",
    confirmation_text: "パスワードが更新されました",
  },
};
